sudo: required

language: go

go:
  - "1.14"

services:
  - docker

cache:
  directories:
    - $GOPATH/pkg/mod

env:
  global:
    - GOBUILD="linux-amd64 windows-amd64 darwin-amd64"

script:
  - GOBUILD=${GOBUILD} make -j build
  - ls -la build/

after_success:
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then make -j docker TAG=pr-$TRAVIS_PULL_REQUEST COMMIT=$TRAVIS_COMMIT; fi
  - if [[ "$BRANCH" == "master" ]]; then make -j docker TAG=latest COMMIT=$TRAVIS_COMMIT; fi
  - if [ -n "$TRAVIS_TAG" ]; then make -j docker TAG=$TRAVIS_TAG COMMIT=$TRAVIS_COMMIT; fi

deploy:
  - provider: releases
    api_key:
      secure: my5mVI1iHm2tdC13nyz/+y47UoVwBcsAEwMGSzcdafzAiOGuQosYO8aOnjK2tq7k0qPtD4PMu/mtFbFkCN7k+82OXMp8ZelsTr1sfK/bnHrPtIcHAaG7eZ6JA5McrYypkekyhsqH/4uaAMITidduKemA+zLgYIeUbWjLQNS2mgvF50BQaW37TsD2dFgB1f1eEGmCbl7jIH7iv23cFrjPnXhScS2AgdWEefy1BhABheV1i7Ucr2LNqzLYliiaWmNAb6ZccCMOo8F0/HQvUCR/mphwgo3LFum55wwycuzH/ZPMF50/fTm/TbOIHDjPxSetqfC1954mTleDJUnxkllINV6HI+gLMex+jsdtBbBw64RvvFspJm2BUNrXn02ZBeqrCHLfL9CKzqnbrTMEFwABdYwUGMWL+FaLB1nNfrAm90btZO1CjlqhgPWtDdES47xu/s5uTtQx2+7IMTKPgkrfvtl0MrsprxzFM9utOQ6mGNUrULaixIRq9ZcwiwJaEDrpksLjOFqBgoUAqDcMFlIeNZ0HZ2q2G1BhoYstSBKUYHxEp7eRZO3HrDCtzQrAfeIiEN5zfeDloJYtOSDcZITNyvG+CS+jOqm+U6r6pXCtjWX9hV0NaCTAx7Eq1fw8eChaJgZTnLyMbjxOf+U5ibwcgo0Rwb2bAOLojVbW6DilqvA=
    file:
      - build/go-metadataproxy-linux-amd64
      - build/go-metadataproxy-windows-amd64
      - build/go-metadataproxy-darwin-amd64
    skip_cleanup: true
    overwrite: true
    on:
      repo: jippi/go-metadataproxy
      tags: true
